# Core Historical configuration used for chains where extra data field has at most 32 bytes
k_at_depth: [23, 22, 22, 20, 21, 20, 20, 21, 20, 20, 21, 22, 19]
max_extra_data_bytes: 32
params:
  node_type:
    Evm: 1
  depth: 17
  initial_depth: 7
