Subquery:
  Account:
    Leaf:
      k: 16
      core_params:
        capacity: 33
      loader_params:
        - comp_loader_params: # keccak
            max_height: 0
            shard_caps:
              - 200
        - comp_loader_params: # header
            max_height: 0
            shard_caps:
              - 33
