SubqueryAgg:
  k: 21
  deps:
    - Header:
        Leaf:
          k: 20
          core_params:
            max_extra_data_bytes: 32
            capacity: 33
          loader_params:
            - comp_loader_params: # keccak
              max_height: 0
              shard_caps:
              - 1000

    - Receipt:
        Leaf:
          k: 20
          core_params:
            chip_params:
              max_data_byte_len: 512
              max_log_num: 20
              topic_num_bounds:
                - 0
                - 4
              network: null
            capacity: 8
          loader_params:
            - comp_loader_params: # keccak
                max_height: 0
                shard_caps:
                  - 1000
            - comp_loader_params: # header
                max_height: 0
                shard_caps:
                  - 33
