[package]
name = "component-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.43"
quote = "1.0.33"
proc-macro2 = "1.0.72"

[lib]
proc-macro = true
