name: Tests

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    paths:
      - "axiom-eth/**" # axiom-eth changes affect axiom-core
      - "axiom-core/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest-64core-256ram

    steps:
      - uses: actions/checkout@v3

      - name: Run axiom-core tests
        working-directory: "axiom-core"
        run: |
          export ALCHEMY_KEY=${{ secrets.ALCHEMY_KEY }}
          export JSON_RPC_URL=${{ secrets.JSON_RPC_URL }}
          cargo t
