# The total subquery capacity is 32
AxiomAgg2:
  k: 23
  force_params:
    num_advice: 1
    num_lookup_advice: 1
    num_fixed: 1
  axiom_agg1_intent:
    k: 22
    force_params:
      num_advice: 13
      num_lookup_advice: 2
      num_fixed: 1
    intent_verify_compute:
      k: 22
      core_params:
        subquery_results_capacity: 32
        svk: "0100000000000000000000000000000000000000000000000000000000000000"
        client_metadata:
          version: 0
          numAdvicePerPhase: [4]
          numLookupAdvicePerPhase: [1]
          numRlcColumns: 0
          numFixed: 1
          numInstance: [2304]
          numChallenge: [0]
          maxOutputs: 128
          isAggregation: false
        preprocessed_len: 13
      loader_params:
        comp_loader_params: # keccak
          max_height: 1
          shard_caps:
            - 4000
    intent_keccak:
      Node:
        k: 21
        num_children: 1
        child_intent:
          Leaf:
            k: 20
            core_params:
              capacity: 4000
    intent_subquery_agg:
      k: 21
      deps:
        - Header:
            Leaf:
              k: 21
              core_params:
                max_extra_data_bytes: 32
                capacity: 33
              loader_params:
                comp_loader_params: # keccak
                  max_height: 1
                  shard_caps:
                    - 4000

        - Account:
            Leaf:
              k: 21
              core_params:
                capacity: 9
                max_trie_depth: 14
              loader_params:
                - comp_loader_params: # keccak
                    max_height: 1
                    shard_caps:
                      - 4000
                - comp_loader_params: # header
                    max_height: 1
                    shard_caps:
                      - 33

        - Storage:
            Leaf:
              k: 21
              core_params:
                capacity: 9
                max_trie_depth: 13
              loader_params:
                - comp_loader_params: # keccak
                    max_height: 1
                    shard_caps:
                      - 4000
                - comp_loader_params: # account
                    max_height: 1
                    shard_caps:
                      - 9
        - Tx:
            Leaf:
              k: 21
              core_params:
                chip_params:
                  max_data_byte_len: 8192
                  max_access_list_len: 4096
                  enable_types:
                    - true
                    - true
                    - true
                capacity: 8
                max_trie_depth: 6
              loader_params:
                - comp_loader_params: # keccak
                    max_height: 1
                    shard_caps:
                      - 4000
                - comp_loader_params: # header
                    max_height: 1
                    shard_caps:
                      - 33

        - Receipt:
            Leaf:
              k: 21
              core_params:
                chip_params:
                  max_data_byte_len: 800
                  max_log_num: 20
                  topic_num_bounds:
                    - 0
                    - 4
                capacity: 8
                max_trie_depth: 6
              loader_params:
                - comp_loader_params: # keccak
                    max_height: 1
                    shard_caps:
                      - 4000
                - comp_loader_params: # header
                    max_height: 1
                    shard_caps:
                      - 33

        - SolidityMapping:
            Leaf:
              k: 21
              core_params:
                capacity: 8
              loader_params:
                - comp_loader_params: # keccak
                    max_height: 1
                    shard_caps:
                      - 4000
                - comp_loader_params: # storage
                    max_height: 1
                    shard_caps:
                      - 9

        - ResultsRoot:
            Leaf:
              k: 21
              core_params:
                enabled_types:
                  - false # Null
                  - true # Header
                  - true # Account
                  - true # Storage
                  - true # Transaction
                  - true # Receipt
                  - true # SolidityNestedMapping
                capacity: 32
              loader_params:
                - comp_loader_params: # keccak
                    max_height: 1
                    shard_caps:
                      - 4000
                - params_per_component:
                    "axiom-query:ComponentTypeHeaderSubquery":
                      max_height: 1
                      shard_caps:
                        - 33
                    "axiom-query:ComponentTypeAccountSubquery":
                      max_height: 1
                      shard_caps:
                        - 9
                    "axiom-query:ComponentTypeStorageSubquery":
                      max_height: 1
                      shard_caps:
                        - 9
                    "axiom-query:ComponentTypeTxSubquery":
                      max_height: 1
                      shard_caps:
                        - 8
                    "axiom-query:ComponentTypeReceiptSubquery":
                      max_height: 1
                      shard_caps:
                        - 8
                    "axiom-query:ComponentTypeSolidityNestedMappingSubquery":
                      max_height: 1
                      shard_caps:
                        - 8
